export enum Variable {
  REACT_APP_ALGORAND_APPID = "REACT_APP_ALGORAND_APPID",
  REACT_APP_ALGORAND_ALGOD_TOKEN = "REACT_APP_ALGORAND_ALGOD_TOKEN",
  REACT_APP_ALGORAND_ALGOD_PORT = "REACT_APP_ALGORAND_ALGOD_PORT",
  REACT_APP_ALGORAND_ALGOD_SERVER = "REACT_APP_ALGORAND_ALGOD_SERVER",
}

export function getVariable<T = string>(variable: Variable): T {
  return process.env[variable] as T;
}
